---
title: "Raster Exercise - MODIS Satellite Imagery"
author: "Alexandre Bevington"
date: "October 27, 2019"
output: html_document
---

<!--

  Copyright 2019 Province of British Columbia

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and limitations under the License.

-->


## Load libraries

```{r}

library(magick)
library(RStoolbox)
library(sf)
library(tidyverse)
library(bcmaps)
library(raster)
```

## Import MODIS NDVI

```{r}
# Get data
  unzip("../data/20191106_Day_2_PM_Raster/raster_modis.zip", exdir = "../data/20191106_Day_2_PM_Raster")

# Make a list of the "TIF" files in a directory of interest (only one in this case)
  files <- list.files(path = "../data/20191106_Day_2_PM_Raster/raster_modis/ndvi", pattern = ".tif$", full.names = T)
  files

# Raster stack
  modis <- stack(files)
  names(modis)

# Plot
  plot(modis[[1]])

```


## Clip stack to BC boundary

```{r rastermask}

# Import AOI 
  bc <- bc_bound() %>% st_transform(crs(modis)) 

# Crop MODIS to AOI extent
  modis_crop <- crop(modis, extent(bc))

# Mask to bc_bound
  modis_mask <- mask(modis_crop, bc)

# Plot first band
  plot(modis_mask[[1]])
  
```

## Plot raster with using a function

```{r plotting-loop}

# Plotting function
  myplot <- function(raster, maxpix = 1e5, outdpi = 150)
    {
      # for debugging
        # raster <- modis_mask[[1]] 
      
      # Name and Date
        name <- sub("X", "", names(raster))
        date <- format(as.Date.character(name, "%Y%m%d"), "%d %b %Y")
      
      # Plotting
        final.plot <- ggR(raster, geom_raster = T, maxpixels = maxpix, ) + 
          geom_sf(data = bc, fill = NA, color = "black") + 
          labs(x = "", y = "", title = date) +
          scale_fill_gradientn(colors=RColorBrewer::brewer.pal(n = 9, name = "BuGn"), guide = FALSE, na.value = NA) +
          theme_minimal(); 
        
      # Print Status
        print(paste0("saving plot ", names(raster)))
      
      # Export 
        ggsave(plot = final.plot, filename = paste0("../data/20191106_Day_2_PM_Raster/raster_modis/",name,"_",as.character(maxpix),"_",outdpi,"_","out.png"),
           width = 8, height=8, dpi = outdpi, device = "png")

    }

  myplot(modis_mask[[1]], maxpix = 1e4, outdpi = 150)
  
```

## Loop the plot function for all rasters

```{r loopplots, eval=F}

# Loop plot export
  for(i in names(modis_mask)){myplot(modis_mask[[i]], maxpix = 1e4, outdpi = 150)}
    
```

## Create a GIF animation

```{r plots-to-gif, eval=F}

# List png iles
  exported_png <- list.files(path = "../data/20191106_Day_2_PM_Raster/raster_modis/", 
                             pattern = "*.png", full.names = T) 
  exported_png
  
# Export GIF (can be slow)
  exported_png %>% 
    map(image_read) %>%
    image_join() %>% 
    image_animate(fps=3) %>% 
    image_write( "../data/20191106_Day_2_PM_Raster/raster_modis/ndvi_timelapse.gif")

```

## Plot time series data for 2 cities

```{r timeseries}

# Import points for Prince George and Victoria
  cities <- bcmaps::bc_cities() %>% 
    filter(NAME %in% c("Prince George", "Victoria"))

# Extract raster values for each point 
  cities_modis <- raster::extract(modis_mask, cities, sp = T) %>% as_tibble()

# Gather the values and correct the formate the dates
  cities_modis_clean <- cities_modis %>% 
    gather("MODIS","Values",contains("MODIS")) %>% 
    dplyr::select(NAME, MODIS, Values) %>% 
    mutate(MODIS_DATE = as.Date.character(sub("_MODIS", "", sub("X","",MODIS)), format = "%Y%m%d"))

# Plot the time series
  ggplot(cities_modis_clean, aes(MODIS_DATE, Values/10000, group = NAME)) + 
    geom_line(linetype = 2, aes(color = NAME)) +
    geom_hline(yintercept = 0.4) +
    geom_point(aes(shape = NAME, color = NAME), size = 3) +
    scale_x_date() +
    scale_color_manual(values = c("red","blue")) + 
    theme_bw() + 
    labs(x = "Date", y = "NDVI")

```
